var companyNames = {
    "FEFF": "GN Netcom",
    "FEFE": "GN ReSound A/S​",
    "FEFD": "​Gimbal, Inc.",
    "FEFC": "Gimbal, Inc.",
    "FEFB": "​Stollmann E+V GmbH",
    "FEFA": "​PayPal, Inc.",
    "FEF9": "​PayPal, Inc.",
    "FEF8": "​Aplix Corporation",
    "FEF7": "​​Aplix Corporation",
    "FEF6": "​Wicentric, Inc.",
    "FEF5": "​Dialog Semiconductor GmbH",
    "FEF4": "​Google",
    "FEF3": "​Google",
    "FEF2": "​CSR",
    "FEF1": "​CSR",
    "FEF0": "Intel",
    "FEEF": "​Polar Electro Oy",
    "FEEE": "​​Polar Electro Oy",
    "FEED": "Tile, Inc.​",
    "FEEC": "​Tile, Inc. ",
    "FEEB": "Swirl Networks, Inc.​",
    "FEEA": "​Swirl Networks, Inc.",
    "FEDB​": "​Perka, Inc.",
    "FEDA": "​ISSC Technologies Corporation",
    "FED9": "​Pebble Technology Corporation",
    "FED8​": "Google​",
    "FEB3": "Taobao​",
    "FEA6": "​GoPro, Inc."
    "FEE9​": "Quintic Corp.​",
    "FEE8​": "Quintic Corp.​",
    "FEE7​": "Tencent Holdings Limited​",
    "FEE6​": "Seed Labs, Inc.",
    "FEE5​": "Nordic Semiconductor ASA​",
    "FEE4​": "Nordic Semiconductor ASA​",
    "FEE3": "Anki, Inc.​",
    "FEE2": "​Anki, Inc.",
    "FEE1​": "​Anhui Huami Information Technology Co.",
    "FEE0": "​Anhui Huami Information Technology Co. ",
    "FEDF​": "Design SHIFT​",
    "FEDE": "Coin, Inc.​",
    "FEDD": "​Jawbone",
    "FEDC": "​Jawbone",
    "FED7": "Broadcom​ Corporation",
    "FED6": "​Broadcom Corporation",
    "FED5​": "​Plantronics Inc.",
    "FED4": "​Apple, Inc.",
    "FED3": "​​Apple, Inc.",
    "FED2": "​​Apple, Inc.",
    "FED1": "​​Apple, Inc.",
    "FED0": "​​Apple, Inc.",
    "FECF": "​​Apple, Inc.",
    "FECE": "​​Apple, Inc.",
    "FECD": "​​Apple, Inc.",
    "FECC": "​​Apple, Inc.",
    "FECB": "​​Apple, Inc.",
    "FECA": "​​Apple, Inc.",
    "FEC9": "​​Apple, Inc.",
    "FEC8": "​​Apple, Inc.",
    "FEC7": "​​Apple, Inc.",
    "FEC6": "​Kocomojo, LLC",
    "FEC5": "Realtek Semiconductor Corp.​",
    "FEC4": "​PLUS Location Systems",
    "FEC3": "​360fly, Inc. ",
    "FEC2": "​Blue Spark Technologies, Inc. ",
    "FEC1": "​KDDI Corporation",
    "FEC0": "​KDDI Corporation",
    "FEBF": "​Nod, Inc. ",
    "FEBE": "​Bose Corporation",
    "FEBD": "​Clover Network, Inc. ",
    "FEBC": "Dexcom, Inc. ​",
    "FEBB": "​adafruit industries",
    "FEBA​": "Tencent Holdings Limited​",
    "FEB9": "LG Electronics​",
    "FEB8": "​Facebook, Inc.",
    "FEB7": "​Facebook, Inc.",
    "FEB6": "​Vencer Co, Ltd",
    "FEB5​": "WiSilica Inc.​",
    "FEB4": "​WiSilica Inc.",
    "​FEB3": "Taobao​",
    "FEB2": "​Microsoft Corporation",
    "FEB1​": "Electronics Tomorrow Limited​",
    "FEB0​": "Nest Labs Inc.​",
    "FEAF​": "Nest Labs Inc.​",
    "FEAE​": "Nokia ​Corporation",
    "FEAD": "​Nokia ​Corporation",
    "FEAC": "​Nokia ​Corporation",
    "FEAB": "​Nokia ​Corporation",
    "FEAA​": "Google​",
    "FEA9": "​Savant Systems LLC",
    "FEA8": "​Savant Systems LLC",
    "FEA7": "​UTC Fire and Security",
    "​FEA6": "​GoPro, Inc."
    "FEA5": "​GoPro, Inc.",
    "FEA4": "Paxton Access Ltd",
    "FEA3": "​ITT Industries",
    "FEA2": "Intrepid Control Systems, Inc.",
    "FEA1": "Intrepid Control Systems, Inc.",
    "FEA0": "Google​",
    "FE9F": "​Google",
    "FE9E": "​Dialog Semiconductor B.V.",
    "FE9D": "Mobiquity Networks Inc​",
    "FE9C": "GSI Laboratories, Inc.​",
    "FE9B": "​Samsara Networks, Inc",
    "FE9A": "​Estimote",
    "FE99": "​Currant, Inc.",
    "FE98": "​Currant, Inc.",
    "FE97": "​Tesla Motor Inc.",
    "FE96": "​Tesla Motor Inc.",
    "FE95": "​Xiaomi Inc.",
    "FE94": "​OttoQ Inc.",
    "FE93": "​​OttoQ Inc.",
    "FE92": "​Jarden Safety & Security",
    "FE91": "​Shanghai Imilab Technology Co.,Ltd",
    "FE90": "JUMA",
    "FE8F": "CSR​",
    "FE8E": "​ARM Ltd",
    "FE8D": "​Interaxon Inc."
}

module.exports.companyNames = companyNames;